var oneschema = {
    "note": "string of the actual note",
    "category": "string of a hierarchy to organize the note where each level|is|a|pipe",
    "deadline": "timestamp when the note has a due date and time",
    "tags": "string of hashtags #that#can#beused#tofilter#notes",
    "order": "number which is used for sort order",
    "created": "timestamp when the note was created",
    "id": "a unique ID automatically generated so that no one note is the same"
    
}
var dataLocal; //the data from localStorage, the real saved data, in string
var data; //data to be used by the tool in JSON
var dataNotes; //an array of all of the notes

function initializeTest() {
    // testing
    wipe();
    load();
    generateRandomNotes(3);
    save();
    log();
}
//initializeTest();

function load() {
    // load data from the real data, localStorage
    dataLocal = localStorage.getItem("data");
    data = JSON.parse(dataLocal);
    dataNotes = data.data;
}

function wipe() {
    // completely wipe out the data
    localStorage.setItem("data", '{"data":[]}');
}

function add(options) {
    // add a note
    var note = {};
    for (var key in oneschema) {
        options[key] ? note[key] = options[key] : null;
    }
    
    // add autogenerated metadata
    note["created"] = new Date().toISOString();
    note["id"] = ""+Date.now() + ""+Math.floor(Math.random() * 10000000000000000);
    
    dataNotes.push(note);
}

function remove(id) {
	dataNotes.splice(get(id), 1);
}

function get(id) {
	var index = dataNotes.findIndex(function(element, index, array) {
		return element.id == id;
	}, this);
	return index;
}

function save() {
    // save data to real data, localStorage
    dataLocal = JSON.stringify(data);
    localStorage.setItem("data", dataLocal);
}

function order() {
    dataNotes = dataNotes.sort(function(a, b) {
        return a.order - b.order;
    });
}

function log() {
    console.log(localStorage.getItem("data"));
    console.log(dataLocal);
    console.log(data);
    console.log(dataNotes);
}

// for testing
function generateRandomNotes(count) {
    // generate a random amount of notes for testing purposes
    for (var i = 0; i < count; i++) {
        add({"note": ""+i});
    }
}