var oneschema = {
    "note": "string of the actual note",
    "category": "string of a hierarchy to organize the note where each level|is|a|pipe",
    "deadline": "timestamp when the note has a due date and time",
    "tags": "string of hashtags #that#can#beused#tofilter#notes",
    "created": "timestamp when the note was created",
    "id": "a unique ID automatically generated so that no one note is the same"
    
}
var data; //data to be used by the tool in JSON
var dataLocal; //the data from localStorage, the real saved data, in string
var dataNotes; //an array of all of the notes

function initializeTest() {
    // testing
    wipe();
    load();
    generateRandomNotes(3);
    save();
    log();
}
//initializeTest();

function load() {
    // load data from the real data, localStorage
    dataLocal = localStorage.getItem("data");
    data = JSON.parse(dataLocal);
    dataNotes = data.data;
}

function wipe() {
    // completely wipe out the data
    localStorage.setItem("data", '{"data":[]}');
}

function add(options) {
    // add a note
    var note = {};
    for (var key in oneschema) {
        options[key] ? note[key] = options[key] : null;
    }
    
    // add autogenerated metadata
    note["created"] = new Date().toISOString();
    note["id"] = ""+Date.now() + ""+Math.floor(Math.random() * 10000000000000000);
    
    dataNotes.push(note);
}

function save() {
    // save data to real data, localStorage
    dataLocal = JSON.stringify(data);
    localStorage.setItem("data", dataLocal);
}

function log() {
    console.log(localStorage.getItem("data"));
    console.log(dataLocal);
    console.log(data);
    console.log(dataNotes);
}

function generateRandomNotes(count) {
    // generate a random amount of notes for testing purposes
    for (var i = 0; i < count; i++) {
        add({"note": ""+i});
    }
}

// i think below is its own JS file because the above should be shared with all apps right?
var noteElements = document.getElementsByTagName("article");
var notesElement = document.getElementById("notes");
var noteTemplate = document.getElementById("noteTemplate");
var noteInput = document.getElementById("noteInput");
var keyboardListener = document.addEventListener("keypress", keyboard);
//var currentFocus;
//var idCount = 1;

function initialize() {
    load();
    render();
}
initialize();

function render() {
    for (var i = 0; i < dataNotes.length; i++) {
        var elementGhost = noteTemplate.content.cloneNode(true);
        notesElement.appendChild(elementGhost);
        var newElement = noteElements[noteElements.length - 1];
        newElement.innerHTML = dataNotes[i].note;
    }
}

function clearDisplay() {
    while (notesElement.firstChild) notesElement.removeChild(notesElement.firstChild);
}

function keyboard(e) {
    if (e.keyCode == 13) {
        e.preventDefault();
        addNote();
    }
}

function addNote() {
    var note = noteInput.value;
    add({"note": ""+note});
    noteInput.value = '';
    save();
    load();
    clearDisplay();
    render();
}